### ISSUE TITLE
Provisionar VM no GCP

### ISSUE THREAD

**Issue by KGurito** [KGurito/AnaliseDeQueimadas#1]
Criação de VM no GCP para desenvolvimento privado e em conjunto. A instância deverá ser a base para a criação de notebooks para análise exploratória e processamento dos dados.

OBS:
Instância Google Colab ou Jupyter.

**Comment by otamori** [comment]
Notebook criado

**Comment by KGurito** [comment]
Notebook criado e conectado ao servidor para processamento.
VM: queimadas-salesperformance-vm
![Captura de tela 2024-11-06 184422](https://github.com/user-attachments/assets/13d4adf6-8cc0-453c-abc9-5b99b2949f3e)
