### ISSUE TITLE
Busca de Base de Dados

### ISSUE THREAD

**Issue by KGurito** [KGurito/AnaliseDeQueimadas#2]
Necessário a busca de uma base de dados confiável para o desenvolvimento do projeto.

**Comment by angels301** [comment]
Base de dados baixada do site oficial do Instituto Nacional de Pesquisas Espaciais (INPE).
https://dataserver-coids.inpe.br/queimadas/queimadas/focos/csv/mensal/Brasil/

As bases são separadas por mês e disponibilizadas apenas do último ano. Nelas, contém os dados como município, estado, número de dias sem chuva, risco de fogo, bioma e FRP (Fire Radiative Power).
